name: Swift

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Swift
    runs-on: macos-latest

    steps:
      - name: Install Dependencies
        run: |
          brew install homebrew/cask/swift swiftlint tuist
          tuist version # Verify tuist installation

      - uses: actions/checkout@v4

      - name: Select Xcode 16.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0' # Or a later version

      - name: SwiftLint
        run: |
          swiftlint --version
          swiftlint --fix --quiet && git diff
          swiftlint --quiet | tee swiftlint.out.txt

      - name: Failing SwiftLint rules
        shell: python
        run: |
          with open("swiftlint.out.txt") as in_file:
            errors = set(line.rsplit("(")[-1][:-2] for line in in_file if line.strip().endswith(")"))
          print(f"{len(errors) = }\ndisabled_rules:")
          print("  - " + "\n  - ".join(sorted(errors)))

      - name: Tuist Install
        run: tuist install

      - name: Generate Xcode Project (Tuist)
        run: tuist generate

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build Xcode Project
        run: xcodebuild -scheme Cork -destination 'platform=macOS' -enablePlugins YES

      - name: Run Tests
        run: xcodebuild -scheme CorkTests -destination 'platform=macOS' -enablePlugins YES test
