name: Build Swift App (Tuist)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14  # macOS with Xcode 17 support

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 17.0
        run: sudo xcode-select -switch /Applications/Xcode_17.0.app/Contents/Developer

      - name: Cache Tuist
        uses: actions/cache@v4
        with:
          path: ~/.tuist
          key: ${{ runner.os }}-tuist-${{ hashFiles('**/Tuist/Project.swift') }}
          restore-keys: |
            ${{ runner.os }}-tuist-

      - name: Install Tuist
        run: |
          curl -Ls https://install.tuist.io | bash
          echo "$HOME/.tuist/bin" >> $GITHUB_PATH

      - name: Fetch Tuist Dependencies
        run: tuist fetch

      - name: Generate Xcode Project
        run: tuist generate

      - name: Run SwiftLint (via Plugin)
        run: |
          swift package resolve
          swift package plugin --allow-writing-to-package-directory lint

      - name: Build the App
        run: |
          xcodebuild clean build \
          -project Cork.xcodeproj \
          -scheme Cork \
          -sdk macosx \
          -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Archive App
        run: |
          xcodebuild archive \
          -project Cork.xcodeproj \
          -scheme Cork \
          -archivePath build/Cork.xcarchive \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Export the App Binary
        run: |
          xcodebuild -exportArchive \
          -archivePath build/Cork.xcarchive \
          -exportOptionsPlist Tuist/ExportOptions.plist \
          -exportPath build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cork-Binary
          path: build/
